spring:
  application:
    name: binwoo-oauth
  datasource:
    url: jdbc:postgresql://binwoo.cn:5432/db_oauth
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    druid:
      validation-query: select 1
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      filters: stat,wall
      initialSize: 5
      maxActive: 20
      maxPoolPreparedStatementPerConnectionSize: 20
      maxWait: 60000
      minEvictableIdleTimeMillis: 300000
      minIdle: 5
      poolPreparedStatements: true
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    change-log: classpath:oauth/master.xml
logging:
  path: ${user.home}/${spring.application.name}

# OAuth配置
oauth:
  jwt:
    signing-key: 123456
  resource:
    id: 123
    exclude: /swagger-ui.html,/swagger-resources/**,/images/**,/webjars/**,/v2/api-docs

server:
  servlet:
    context-path: /api
  port: 9979
