spring:
  application:
    name: binwoo-oauth
logging:
  path: ${user.home}/${spring.application.name}

oauth:
  jwt:
    signing-key: 123456
  resource:
    id: 123
    exclude: /swagger-ui.html,/swagger-resources/**,/images/**,/webjars/**,/v2/api-docs

server:
  servlet:
    context-path: /api
  port: 9979
